services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: caspian
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: caspian_db
    ports:
        - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://caspian:12345@db:5432/caspian_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: